logging:
  level: debug
  formatter: TXT

api:
  server_host: 0.0.0.0
  server_port: 9092

k8s_api_server_uri: localhost:4443

plugin:
  check_interval: 10s
  check_timeout: 2s

etcd:
  endpoints:
    - localhost:2379
