name: analyze
version: 0.0.1
appVersion: "v0.0.1"
apiVersion: v1
description: Analyze service. Checks your k8s cluster and makes suggestions how to save your money!
icon: https://raw.githubusercontent.com/elastic/kibana/master/src/ui/public/icons/kibana-color.svg
keywords:
- kubernetes
- k8s
- supergiant
- qbox
maintainers:
- name: taaraora
  email: dmytro@qbox.io
sources:
- https://github.com/supergiant/robot
home: https://supergiant.io/